# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f1kaaCHUFtXKd5Ty_J1gvkBtNFz-YG50
"""

#dictionary 
# Create a library class
class Library:
    def __init__(self, list, name):
        self.booksList = list
        self.name = name
        self.lendDict = {}

    def displayBooks(self):         #Create display book function
        print(f"We have following books in our library: {self.name}")
        for book in self.booksList:
            print(book)

    def lendBook(self, user, book):     #Create lend book function
        if book not in self.lendDict.keys():
            self.lendDict.update({book:user})
            print("Lender-Book database has been updated. You can take the book now")
        else:
            print(f"Book is already being used by {self.lendDict[book]}")

    def addBook(self, book):      #Create add book function
        self.booksList.append(book)
        print("Book has been added to the book list")
#Create return  book function
    def returnBook(self, book):
        self.lendDict.pop(book)
# IUBLibrary = Library(listofbooks, library_name)
if __name__ == '__main__':
    IUB = Library(['Python', 'Rich Daddy Poor Daddy', 'harry Potter', 'C++ Basics', 'Algorithms by CLRS','Introduction to Anthropology',	'Introduction to Sociology', 'Health and Society', 'Social Psychology', 'Introduction to Econ', 'Introduction to Communication', 'Listening and Speaking Skills', 'English Reading Skills', 'Business English', 'Introduction to Computer Programming', 'Calculus and Analytical Geometry', 'Probability & Statistics for Science and Engineering'], "IUB")
# create a main function and run an infinite while loop asking
    while(True):
        print(f"Welcome to the {IUB.name} library. Enter your choice to continue")
        print("1. Display Books")   #choices for user
        print("2. Lend a Book")
        print("3. Add a Book")
        print("4. Return a Book")
        # users for their input
        user_choice = input()
        if user_choice not in ['1','2','3','4']:
            print("Please enter a valid option")
            continue

        else:
            user_choice = int(user_choice)


        if user_choice == 1:
            IUB.displayBooks()

        elif user_choice == 2:
            book = input("Enter the name of the book you want to lend:")
            user = input("Enter your name")
            IUB.lendBook(user, book)

        elif user_choice == 3:
            book = input("Enter the name of the book you want to add:")
            IUB.addBook(book)

        elif user_choice == 4:
            book = input("Enter the name of the book you want to return:")
            IUB.returnBook(book)

        else:
            print("Not a valid option")


        print("Press q to quit and c to continue")
        user_choice2 = ""
        while(user_choice2!="c" and user_choice2!="q"):
            user_choice2 = input()
            if user_choice2 == "q":
                exit()

            elif user_choice2 == "c":
                continue

